### ISSUE TITLE
how to make the live streaming?

### ISSUE THREAD

**Issue by gumuruhsspj** [PHPVibe/phpvibe-lite#13]
i wonder if there's a complete documentation of 
PhpVibe API for live stream?

**Comment by PHPVibe** [comment]
Never had live streaming.

**Comment by ROBERT-MCDOWELL** [comment]
will it be available? why not to use peer 2 peer webtorrent or IPFS to light servers?

**Comment by PHPVibe** [comment]
> will it be available? why not to use peer 2 peer webtorrent or IPFS to light servers?

No plan for such. This has become a hobby project. This particular version is discontinued.

**Comment by ROBERT-MCDOWELL** [comment]
would you like I fork it and work on it to integrate the p2p tech?

**Comment by PHPVibe** [comment]
> would you like I fork it and work on it to integrate the p2p tech?

Be my guest!

**Comment by ROBERT-MCDOWELL** [comment]
Great!, I saw you have several versions of phpvibe, is the git repo the one that have all features?
if yes, so I can have a good base to start.

**Comment by ROBERT-MCDOWELL** [comment]
also would you be ready to improve your UI project if needed?

**Comment by PHPVibe** [comment]
We're working on a full remake of the commercial version. 
This one is abandoned. 
It's old and won't get upgrades.

Both available right now we'll be replaced by a modular commercial version (very cheap/free CMS + commercial plugins).

**Comment by ROBERT-MCDOWELL** [comment]
@PHPVibe
ok so please let me have access to the new sources son I can start to work on it when realease finished.

**Comment by gumuruhsspj** [comment]
> @PHPVibe ok so please let me have access to the new sources son I can start to work on it when realease finished.

alright... wish that could be happened.
