### ISSUE TITLE
Cannot uplaod a video

### ISSUE THREAD

**Issue by KaratekHD** [PHPVibe/phpvibe-lite#3]
![Screenshot-2019-5-14 share](https://user-images.githubusercontent.com/38097062/57697327-3bd9bf80-7653-11e9-8188-a9d3fa4d69e1.png)
Hello,

I cannot find a way to upload  a video. I click on the arrow icon on the top but after that, I can 
only embed a Video from another server. There is just no button for uploading a video. What do I have to do?

Thank you

~KaratekHD

**Comment by PHPVibe** [comment]
Hi! PHPVibe has no video upload functions.
Those are only available in MediaVibe.

**Comment by KaratekHD** [comment]
Alright, thanks!
