### ISSUE TITLE
PHPVibe will silently fail to add videos

### ISSUE THREAD

**Issue by bugz8unny69** [PHPVibe/phpvibe-lite#6]
Videos do not get added when you click add video.

**Expected Result:**

Videos added to Manage Videos

**Actual Result:**

List is empty

**Additional notes:**

```
array (size=2)
          'error_str' => string 'Incorrect integer value: '' for column `phpvibe_db`.`vibe_videos`.`category` at row 1' (length=85)
          'query' => string 'INSERT INTO vibe_videos (`privacy`,`pub`,`source`, `user_id`, `date`, `thumb`, `title`, `duration`, `tags` ,  `liked` , `category`, `description`, `nsfw`, `views`, `featured`) VALUES 
('0','1','https://www.youtube.com/watch?v=Lr8ogzNZ7-0', '1', now() , 'storage/media/thumbs/e887b29a64e92397aa5d70ae6e4b92c4-1.png', 'sssssss', '1403', 'english', '0','','','0','1','0')' (length=368)
```

**Comment by PHPVibe** [comment]
Hi, 

Turn off safe mode in mysql as per the requirements.

**Comment by lhorace** [comment]
There is no input validation for category:

https://github.com/PHPVibe/phpvibe/blob/ae3242c56e7cc354cb1de1418663a69261cf6660/The%20CMS/moderator/add-video.php#L25-L30

Due to table constraints, SQL query fails, and PHPVibe incorrectly reports _success_. Neither there is any check if the SQL query was successful.

**Comment by bugz8unny69** [comment]
https://www.phpvibe.com/requirements/ isn't clear regarding what `Safe_mode Off` is referring to. The assumption here is `PHP Safe Mode`. Additionally, MySQL Safe Mode ref [1], is entirely different issue. Your insert query fails if category is empty due to table constraints.

1. https://www.xpertdeveloper.com/mysql-safe-update/

**Comment by PHPVibe** [comment]
I know, the sql got pretty old after the last updates and restrictions that came with it. It would need a full recheck.

**Comment by PHPVibe** [comment]
Sorry about the requirements not being clear.
