### ISSUE TITLE
Remember me doesn't work

### ISSUE THREAD

**Issue by bugz8unny69** [PHPVibe/phpvibe-lite#8]
Remember me on the login form doesn't work, after a period of time, the session expires and I have to login again?

Steps to reproduce:
1. Login
2. Wait a day or two
3. Refresh page

Expected results:
Remember session

Actual results:
I'm logged out.

**Comment by PHPVibe** [comment]
Hi, 

Go to options, make sure all fields are configured, check the cookie split one also. Put ### or something like this in it.
